spring:
  application:
    name: notification-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    group:
      local: "local,topics"
      dev: "dev,topics,kafka"
      prod: "prod,kafka,topics"
      load-test: "local,topics"
  config:
    import:
      - "optional:configserver: "
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
  kafka:
    listener:
      ack-mode: manual

server:
  port: 9012

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:9001/eureka/}

aws:
  ses:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    send-mail-from: ${ADMIN_EMAIL}
    endpoint-override: ${AWS_SES_ENDPOINT_OVERRIDE:}
  region: ${AWS_REGION}

support:
  email: ${SUPPORT_EMAIL}